//
// ActivityOwnerType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ActivityOwnerType: String, Sendable, Codable, CaseIterable {
    case node = "NODE"
    case user = "USER"
}
