//
// JobsTaskStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum JobsTaskStatus: String, Sendable, Codable, CaseIterable {
    case unknown = "Unknown"
    case idle = "Idle"
    case running = "Running"
    case finished = "Finished"
    case interrupted = "Interrupted"
    case paused = "Paused"
    case any = "Any"
    case error = "Error"
    case queued = "Queued"
}
