//
// RestNodeLocators.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestNodeLocators: Codable, JSONEncodable, Hashable {

    public var many: [RestNodeLocator]?

    public init(many: [RestNodeLocator]? = nil) {
        self.many = many
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case many = "Many"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(many, forKey: .many)
    }

    public static func == (lhs: RestNodeLocators, rhs: RestNodeLocators) -> Bool {
        lhs.many == rhs.many
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(many?.hashValue)
        
    }
}

