//
// RestMetaUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestMetaUpdate: Codable, JSONEncodable, Hashable {

    public var operation: MetaUpdateOp?
    public var userMeta: RestUserMeta?

    public init(operation: MetaUpdateOp? = nil, userMeta: RestUserMeta? = nil) {
        self.operation = operation
        self.userMeta = userMeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case operation = "Operation"
        case userMeta = "UserMeta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(operation, forKey: .operation)
        try container.encodeIfPresent(userMeta, forKey: .userMeta)
    }

    public static func == (lhs: RestMetaUpdate, rhs: RestMetaUpdate) -> Bool {
        lhs.operation == rhs.operation &&
        lhs.userMeta == rhs.userMeta
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(operation?.hashValue)
        hasher.combine(userMeta?.hashValue)
        
    }
}

