//
// RestCountMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestCountMeta: Codable, JSONEncodable, Hashable {

    public var namespace: String
    public var value: Int

    public init(namespace: String, value: Int) {
        self.namespace = namespace
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespace = "Namespace"
        case value = "Value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(namespace, forKey: .namespace)
        try container.encode(value, forKey: .value)
    }

    public static func == (lhs: RestCountMeta, rhs: RestCountMeta) -> Bool {
        lhs.namespace == rhs.namespace &&
        lhs.value == rhs.value
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(namespace.hashValue)
        hasher.combine(value.hashValue)
        
    }
}

