//
// RestNodeCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestNodeCollection: Codable, JSONEncodable, Hashable {

    public var facets: [TreeSearchFacet]?
    public var nodes: [RestNode]
    public var pagination: RestPagination?

    public init(facets: [TreeSearchFacet]? = nil, nodes: [RestNode], pagination: RestPagination? = nil) {
        self.facets = facets
        self.nodes = nodes
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case facets = "Facets"
        case nodes = "Nodes"
        case pagination = "Pagination"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(facets, forKey: .facets)
        try container.encode(nodes, forKey: .nodes)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }

    public static func == (lhs: RestNodeCollection, rhs: RestNodeCollection) -> Bool {
        lhs.facets == rhs.facets &&
        lhs.nodes == rhs.nodes &&
        lhs.pagination == rhs.pagination
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(facets?.hashValue)
        hasher.combine(nodes.hashValue)
        hasher.combine(pagination?.hashValue)
        
    }
}

