//
// RestNamespaceValuesOperation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestNamespaceValuesOperation: Codable, JSONEncodable, Hashable {

    public var operation: RestNsOp?
    public var values: [String]?

    public init(operation: RestNsOp? = nil, values: [String]? = nil) {
        self.operation = operation
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case operation = "Operation"
        case values = "Values"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(operation, forKey: .operation)
        try container.encodeIfPresent(values, forKey: .values)
    }

    public static func == (lhs: RestNamespaceValuesOperation, rhs: RestNamespaceValuesOperation) -> Bool {
        lhs.operation == rhs.operation &&
        lhs.values == rhs.values
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(operation?.hashValue)
        hasher.combine(values?.hashValue)
        
    }
}

