//
// RestFilePreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestFilePreview: Codable, JSONEncodable, Hashable {

    public var contentType: String?
    public var dimension: Int?
    public var processing: Bool?
    public var url: String?

    public init(contentType: String? = nil, dimension: Int? = nil, processing: Bool? = nil, url: String? = nil) {
        self.contentType = contentType
        self.dimension = dimension
        self.processing = processing
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType = "ContentType"
        case dimension = "Dimension"
        case processing = "Processing"
        case url = "Url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(dimension, forKey: .dimension)
        try container.encodeIfPresent(processing, forKey: .processing)
        try container.encodeIfPresent(url, forKey: .url)
    }

    public static func == (lhs: RestFilePreview, rhs: RestFilePreview) -> Bool {
        lhs.contentType == rhs.contentType &&
        lhs.dimension == rhs.dimension &&
        lhs.processing == rhs.processing &&
        lhs.url == rhs.url
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(contentType?.hashValue)
        hasher.combine(dimension?.hashValue)
        hasher.combine(processing?.hashValue)
        hasher.combine(url?.hashValue)
        
    }
}

