//
// RestMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestMode: String, Sendable, Codable, CaseIterable {
    case _default = "Default"
    case nodeReadOnly = "NodeReadOnly"
    case nodeWriteOnly = "NodeWriteOnly"
    case levelReadOnly = "LevelReadOnly"
}
