//
// RestListTemplatesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestListTemplatesResponse: Codable, JSONEncodable, Hashable {

    public var templates: [RestTemplate]?

    public init(templates: [RestTemplate]? = nil) {
        self.templates = templates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templates = "Templates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(templates, forKey: .templates)
    }

    public static func == (lhs: RestListTemplatesResponse, rhs: RestListTemplatesResponse) -> Bool {
        lhs.templates == rhs.templates
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(templates?.hashValue)
        
    }
}

