//
// RestUserActionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestUserActionType: String, Sendable, Codable, CaseIterable {
    case delete = "delete"
    case restore = "restore"
    case copy = "copy"
    case move = "move"
    case extract = "extract"
    case compress = "compress"
}
