//
// RestSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to create a selection from a list of nodes. */
public final class RestSelection: Codable, JSONEncodable, Hashable {

    public var nodes: [RestNode]?
    public var uuid: String?

    public init(nodes: [RestNode]? = nil, uuid: String? = nil) {
        self.nodes = nodes
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nodes = "Nodes"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nodes, forKey: .nodes)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }

    public static func == (lhs: RestSelection, rhs: RestSelection) -> Bool {
        lhs.nodes == rhs.nodes &&
        lhs.uuid == rhs.uuid
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nodes?.hashValue)
        hasher.combine(uuid?.hashValue)
        
    }
}

