//
// RestUserMetaList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestUserMetaList: Codable, JSONEncodable, Hashable {

    public var userMeta: [RestUserMeta]?

    public init(userMeta: [RestUserMeta]? = nil) {
        self.userMeta = userMeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userMeta = "UserMeta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userMeta, forKey: .userMeta)
    }

    public static func == (lhs: RestUserMetaList, rhs: RestUserMetaList) -> Bool {
        lhs.userMeta == rhs.userMeta
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userMeta?.hashValue)
        
    }
}

