//
// RestPublicLinkDeleteSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestPublicLinkDeleteSuccess: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var uuid: String?

    public init(message: String? = nil, uuid: String? = nil) {
        self.message = message
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message = "Message"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }

    public static func == (lhs: RestPublicLinkDeleteSuccess, rhs: RestPublicLinkDeleteSuccess) -> Bool {
        lhs.message == rhs.message &&
        lhs.uuid == rhs.uuid
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(message?.hashValue)
        hasher.combine(uuid?.hashValue)
        
    }
}

