//
// RestCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestCreateRequest: Codable, JSONEncodable, Hashable {

    public var inputs: [RestIncomingNode]?
    public var recursive: Bool?

    public init(inputs: [RestIncomingNode]? = nil, recursive: Bool? = nil) {
        self.inputs = inputs
        self.recursive = recursive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inputs = "Inputs"
        case recursive = "Recursive"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inputs, forKey: .inputs)
        try container.encodeIfPresent(recursive, forKey: .recursive)
    }

    public static func == (lhs: RestCreateRequest, rhs: RestCreateRequest) -> Bool {
        lhs.inputs == rhs.inputs &&
        lhs.recursive == rhs.recursive
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(inputs?.hashValue)
        hasher.combine(recursive?.hashValue)
        
    }
}

