//
// RestBatchUpdateMetaList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestBatchUpdateMetaList: Codable, JSONEncodable, Hashable {

    public var updates: [RestMetaUpdate]?

    public init(updates: [RestMetaUpdate]? = nil) {
        self.updates = updates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updates = "Updates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(updates, forKey: .updates)
    }

    public static func == (lhs: RestBatchUpdateMetaList, rhs: RestBatchUpdateMetaList) -> Bool {
        lhs.updates == rhs.updates
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(updates?.hashValue)
        
    }
}

