//
// ServiceResourcePolicyPolicyEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ServiceResourcePolicyPolicyEffect: String, Sendable, Codable, CaseIterable {
    case deny = "deny"
    case allow = "allow"
}
