//
// TreeGeoPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class TreeGeoPoint: Codable, JSONEncodable, Hashable {

    public var lat: Double?
    public var lon: Double?

    public init(lat: Double? = nil, lon: Double? = nil) {
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lat = "Lat"
        case lon = "Lon"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lon, forKey: .lon)
    }

    public static func == (lhs: TreeGeoPoint, rhs: TreeGeoPoint) -> Bool {
        lhs.lat == rhs.lat &&
        lhs.lon == rhs.lon
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(lat?.hashValue)
        hasher.combine(lon?.hashValue)
        
    }
}

