//
// TreeNodeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TreeNodeType: String, Sendable, Codable, CaseIterable {
    case unknown = "UNKNOWN"
    case leaf = "LEAF"
    case collection = "COLLECTION"
}
