//
// IdmWorkspaceScope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum IdmWorkspaceScope: String, Sendable, Codable, CaseIterable {
    case any = "ANY"
    case admin = "ADMIN"
    case room = "ROOM"
    case link = "LINK"
}
