//
// JobsCommand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum JobsCommand: String, Sendable, Codable, CaseIterable {
    case _none = "None"
    case pause = "Pause"
    case resume = "Resume"
    case stop = "Stop"
    case delete = "Delete"
    case runOnce = "RunOnce"
    case inactive = "Inactive"
    case active = "Active"
}
