//
// LookupFilterTextSearch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupFilterTextSearch: Sendable, Codable, JSONEncodable, Hashable {

    public var searchIn: LookupFilterTextSearchIn?
    public var term: String?

    public init(searchIn: LookupFilterTextSearchIn? = nil, term: String? = nil) {
        self.searchIn = searchIn
        self.term = term
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchIn = "SearchIn"
        case term = "Term"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(searchIn, forKey: .searchIn)
        try container.encodeIfPresent(term, forKey: .term)
    }
}

