//
// LookupFilterStatusFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupFilterStatusFilter: Sendable, Codable, JSONEncodable, Hashable {

    public var deleted: StatusFilterDeletedStatus?
    public var hasPublicLink: Bool?
    public var isBookmarked: Bool?
    public var isDraft: Bool?

    public init(deleted: StatusFilterDeletedStatus? = nil, hasPublicLink: Bool? = nil, isBookmarked: Bool? = nil, isDraft: Bool? = nil) {
        self.deleted = deleted
        self.hasPublicLink = hasPublicLink
        self.isBookmarked = isBookmarked
        self.isDraft = isDraft
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deleted = "Deleted"
        case hasPublicLink = "HasPublicLink"
        case isBookmarked = "IsBookmarked"
        case isDraft = "IsDraft"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deleted, forKey: .deleted)
        try container.encodeIfPresent(hasPublicLink, forKey: .hasPublicLink)
        try container.encodeIfPresent(isBookmarked, forKey: .isBookmarked)
        try container.encodeIfPresent(isDraft, forKey: .isDraft)
    }
}

