//
// LookupFilterPathPrefix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupFilterPathPrefix: Sendable, Codable, JSONEncodable, Hashable {

    public var exclude: Bool?
    public var _prefix: String?

    public init(exclude: Bool? = nil, _prefix: String? = nil) {
        self.exclude = exclude
        self._prefix = _prefix
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exclude = "Exclude"
        case _prefix = "Prefix"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(exclude, forKey: .exclude)
        try container.encodeIfPresent(_prefix, forKey: ._prefix)
    }
}

