//
// LookupFilterMetaFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupFilterMetaFilter: Sendable, Codable, JSONEncodable, Hashable {

    public var namespace: String?
    public var operation: LookupFilterMetaFilterOp?
    public var term: String?

    public init(namespace: String? = nil, operation: LookupFilterMetaFilterOp? = nil, term: String? = nil) {
        self.namespace = namespace
        self.operation = operation
        self.term = term
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespace = "Namespace"
        case operation = "Operation"
        case term = "Term"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(operation, forKey: .operation)
        try container.encodeIfPresent(term, forKey: .term)
    }
}

