//
// LookupFilterSizeRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupFilterSizeRange: Sendable, Codable, JSONEncodable, Hashable {

    public var max: String?
    public var min: String?

    public init(max: String? = nil, min: String? = nil) {
        self.max = max
        self.min = min
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case max = "Max"
        case min = "Min"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(max, forKey: .max)
        try container.encodeIfPresent(min, forKey: .min)
    }
}

