//
// LookupFilterTextSearchIn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LookupFilterTextSearchIn: String, Sendable, Codable, CaseIterable {
    case baseName = "BaseName"
    case contents = "Contents"
    case baseOrContents = "BaseOrContents"
}
