//
// LookupFilterMetaFilterOp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LookupFilterMetaFilterOp: String, Sendable, Codable, CaseIterable {
    case must = "Must"
    case should = "Should"
    case not = "Not"
}
