//
// RestShareLinkTargetUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestShareLinkTargetUser: Codable, JSONEncodable, Hashable {

    public var display: String?
    public var downloadCount: Int?

    public init(display: String? = nil, downloadCount: Int? = nil) {
        self.display = display
        self.downloadCount = downloadCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case display = "Display"
        case downloadCount = "DownloadCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(display, forKey: .display)
        try container.encodeIfPresent(downloadCount, forKey: .downloadCount)
    }

    public static func == (lhs: RestShareLinkTargetUser, rhs: RestShareLinkTargetUser) -> Bool {
        lhs.display == rhs.display &&
        lhs.downloadCount == rhs.downloadCount
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(display?.hashValue)
        hasher.combine(downloadCount?.hashValue)
        
    }
}

