//
// RestVersionCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestVersionCollection: Sendable, Codable, JSONEncodable, Hashable {

    public var versions: [RestVersion]?

    public init(versions: [RestVersion]? = nil) {
        self.versions = versions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case versions = "Versions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(versions, forKey: .versions)
    }
}

