//
// RestActionOptionsDelete.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestActionOptionsDelete: Sendable, Codable, JSONEncodable, Hashable {

    public var permanentDelete: Bool?

    public init(permanentDelete: Bool? = nil) {
        self.permanentDelete = permanentDelete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permanentDelete = "PermanentDelete"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(permanentDelete, forKey: .permanentDelete)
    }
}

