//
// RestDeleteVersionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestDeleteVersionResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var emptyNodeDeleted: Bool?
    public var success: Bool?

    public init(emptyNodeDeleted: Bool? = nil, success: Bool? = nil) {
        self.emptyNodeDeleted = emptyNodeDeleted
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emptyNodeDeleted = "EmptyNodeDeleted"
        case success = "Success"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(emptyNodeDeleted, forKey: .emptyNodeDeleted)
        try container.encodeIfPresent(success, forKey: .success)
    }
}

