//
// RestNodeVersionsFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestNodeVersionsFilter: Sendable, Codable, JSONEncodable, Hashable {

    public var filterBy: RestVersionsTypes?
    public var limit: String?
    public var offset: String?
    public var sortDirDesc: Bool?
    public var sortField: String?

    public init(filterBy: RestVersionsTypes? = nil, limit: String? = nil, offset: String? = nil, sortDirDesc: Bool? = nil, sortField: String? = nil) {
        self.filterBy = filterBy
        self.limit = limit
        self.offset = offset
        self.sortDirDesc = sortDirDesc
        self.sortField = sortField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filterBy = "FilterBy"
        case limit = "Limit"
        case offset = "Offset"
        case sortDirDesc = "SortDirDesc"
        case sortField = "SortField"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filterBy, forKey: .filterBy)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(offset, forKey: .offset)
        try container.encodeIfPresent(sortDirDesc, forKey: .sortDirDesc)
        try container.encodeIfPresent(sortField, forKey: .sortField)
    }
}

