//
// RestBackgroundAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestBackgroundAction: Sendable, Codable, JSONEncodable, Hashable {

    public var canPause: Bool?
    public var canStop: Bool?
    public var endTime: Int?
    public var hasProgress: Bool?
    public var jobUuid: String
    public var label: String?
    public var name: String
    public var progress: Float?
    public var startTime: Int?
    public var status: JobsTaskStatus?
    public var statusMessage: String?

    public init(canPause: Bool? = nil, canStop: Bool? = nil, endTime: Int? = nil, hasProgress: Bool? = nil, jobUuid: String, label: String? = nil, name: String, progress: Float? = nil, startTime: Int? = nil, status: JobsTaskStatus? = nil, statusMessage: String? = nil) {
        self.canPause = canPause
        self.canStop = canStop
        self.endTime = endTime
        self.hasProgress = hasProgress
        self.jobUuid = jobUuid
        self.label = label
        self.name = name
        self.progress = progress
        self.startTime = startTime
        self.status = status
        self.statusMessage = statusMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canPause = "CanPause"
        case canStop = "CanStop"
        case endTime = "EndTime"
        case hasProgress = "HasProgress"
        case jobUuid = "JobUuid"
        case label = "Label"
        case name = "Name"
        case progress = "Progress"
        case startTime = "StartTime"
        case status = "Status"
        case statusMessage = "StatusMessage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(canPause, forKey: .canPause)
        try container.encodeIfPresent(canStop, forKey: .canStop)
        try container.encodeIfPresent(endTime, forKey: .endTime)
        try container.encodeIfPresent(hasProgress, forKey: .hasProgress)
        try container.encode(jobUuid, forKey: .jobUuid)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(progress, forKey: .progress)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(statusMessage, forKey: .statusMessage)
    }
}

