//
// RestPromoteParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPromoteParameters: Sendable, Codable, JSONEncodable, Hashable {

    public var ignoreConflicts: Bool?
    public var publish: Bool?

    public init(ignoreConflicts: Bool? = nil, publish: Bool? = nil) {
        self.ignoreConflicts = ignoreConflicts
        self.publish = publish
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ignoreConflicts = "IgnoreConflicts"
        case publish = "Publish"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ignoreConflicts, forKey: .ignoreConflicts)
        try container.encodeIfPresent(publish, forKey: .publish)
    }
}

