//
// RestActionOptionsCopyMove.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestActionOptionsCopyMove: Sendable, Codable, JSONEncodable, Hashable {

    public var targetIsParent: Bool?
    public var targetPath: String

    public init(targetIsParent: Bool? = nil, targetPath: String) {
        self.targetIsParent = targetIsParent
        self.targetPath = targetPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case targetIsParent = "TargetIsParent"
        case targetPath = "TargetPath"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(targetIsParent, forKey: .targetIsParent)
        try container.encode(targetPath, forKey: .targetPath)
    }
}

