//
// RestNodeLocator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestNodeLocator: Codable, JSONEncodable, Hashable {

    public var path: String?
    public var uuid: String?

    public init(path: String? = nil, uuid: String? = nil) {
        self.path = path
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }

    public static func == (lhs: RestNodeLocator, rhs: RestNodeLocator) -> Bool {
        lhs.path == rhs.path &&
        lhs.uuid == rhs.uuid
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path?.hashValue)
        hasher.combine(uuid?.hashValue)
        
    }
}

