//
// RestBatchUpdateMetaList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestBatchUpdateMetaList: Sendable, Codable, JSONEncodable, Hashable {

    public var updates: [RestMetaUpdate]

    public init(updates: [RestMetaUpdate]) {
        self.updates = updates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updates = "Updates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updates, forKey: .updates)
    }
}

