//
// RestNsOp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestNsOp: String, Sendable, Codable, CaseIterable {
    case put = "PUT"
    case delete = "DELETE"
}
