//
// RestLookupScope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestLookupScope: Sendable, Codable, JSONEncodable, Hashable {

    public var nodes: [RestNodeLocator]?
    public var recursive: Bool?
    public var root: RestNodeLocator?

    public init(nodes: [RestNodeLocator]? = nil, recursive: Bool? = nil, root: RestNodeLocator? = nil) {
        self.nodes = nodes
        self.recursive = recursive
        self.root = root
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nodes = "Nodes"
        case recursive = "Recursive"
        case root = "Root"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nodes, forKey: .nodes)
        try container.encodeIfPresent(recursive, forKey: .recursive)
        try container.encodeIfPresent(root, forKey: .root)
    }
}

