//
// RestMetaUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestMetaUpdate: Sendable, Codable, JSONEncodable, Hashable {

    public var operation: RestMetaUpdateOp
    public var userMeta: RestUserMeta

    public init(operation: RestMetaUpdateOp, userMeta: RestUserMeta) {
        self.operation = operation
        self.userMeta = userMeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case operation = "Operation"
        case userMeta = "UserMeta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(operation, forKey: .operation)
        try container.encode(userMeta, forKey: .userMeta)
    }
}

