//
// RestNodeCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestNodeCollection: Sendable, Codable, JSONEncodable, Hashable {

    public var facets: [TreeSearchFacet]?
    public var nodes: [RestNode]?
    public var pagination: RestPagination?

    public init(facets: [TreeSearchFacet]? = nil, nodes: [RestNode]? = nil, pagination: RestPagination? = nil) {
        self.facets = facets
        self.nodes = nodes
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case facets = "Facets"
        case nodes = "Nodes"
        case pagination = "Pagination"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(facets, forKey: .facets)
        try container.encodeIfPresent(nodes, forKey: .nodes)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

