//
// RestFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestFlag: String, Sendable, Codable, CaseIterable {
    case withMetaDefaults = "WithMetaDefaults"
    case withMetaCoreOnly = "WithMetaCoreOnly"
    case withMetaNone = "WithMetaNone"
    case withVersionsAll = "WithVersionsAll"
    case withVersionsDraft = "WithVersionsDraft"
    case withVersionsPublished = "WithVersionsPublished"
}
