//
// RestLookupFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestLookupFilter: Sendable, Codable, JSONEncodable, Hashable {

    public var date: LookupFilterDateRange?
    public var extensions: [String]?
    public var freeExpression: String?
    public var metadata: [LookupFilterMetaFilter]?
    public var prefixes: [LookupFilterPathPrefix]?
    public var size: LookupFilterSizeRange?
    public var status: LookupFilterStatusFilter?
    public var text: LookupFilterTextSearch?
    public var type: TreeNodeType?

    public init(date: LookupFilterDateRange? = nil, extensions: [String]? = nil, freeExpression: String? = nil, metadata: [LookupFilterMetaFilter]? = nil, prefixes: [LookupFilterPathPrefix]? = nil, size: LookupFilterSizeRange? = nil, status: LookupFilterStatusFilter? = nil, text: LookupFilterTextSearch? = nil, type: TreeNodeType? = nil) {
        self.date = date
        self.extensions = extensions
        self.freeExpression = freeExpression
        self.metadata = metadata
        self.prefixes = prefixes
        self.size = size
        self.status = status
        self.text = text
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date = "Date"
        case extensions = "Extensions"
        case freeExpression = "FreeExpression"
        case metadata = "Metadata"
        case prefixes = "Prefixes"
        case size = "Size"
        case status = "Status"
        case text = "Text"
        case type = "Type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(extensions, forKey: .extensions)
        try container.encodeIfPresent(freeExpression, forKey: .freeExpression)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(prefixes, forKey: .prefixes)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

