//
// RestJsonMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestJsonMeta: Sendable, Codable, JSONEncodable, Hashable {

    public var namespace: String
    public var value: String

    public init(namespace: String, value: String) {
        self.namespace = namespace
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespace = "Namespace"
        case value = "Value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(namespace, forKey: .namespace)
        try container.encode(value, forKey: .value)
    }
}

