//
// RestPerformActionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPerformActionResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var affectedNodes: [RestNode]?
    public var backgroundActions: [RestBackgroundAction]?
    public var status: RestActionStatus?

    public init(affectedNodes: [RestNode]? = nil, backgroundActions: [RestBackgroundAction]? = nil, status: RestActionStatus? = nil) {
        self.affectedNodes = affectedNodes
        self.backgroundActions = backgroundActions
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case affectedNodes = "AffectedNodes"
        case backgroundActions = "BackgroundActions"
        case status = "Status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(affectedNodes, forKey: .affectedNodes)
        try container.encodeIfPresent(backgroundActions, forKey: .backgroundActions)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

