//
// RestPublishCascadeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPublishCascadeResult: Sendable, Codable, JSONEncodable, Hashable {

    public var error: String?
    public var node: RestNode?
    public var promoted: Bool?
    public var success: Bool?

    public init(error: String? = nil, node: RestNode? = nil, promoted: Bool? = nil, success: Bool? = nil) {
        self.error = error
        self.node = node
        self.promoted = promoted
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error = "Error"
        case node = "Node"
        case promoted = "Promoted"
        case success = "Success"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(node, forKey: .node)
        try container.encodeIfPresent(promoted, forKey: .promoted)
        try container.encodeIfPresent(success, forKey: .success)
    }
}

