//
// RestShareLinkAccessType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestShareLinkAccessType: String, Sendable, Codable, CaseIterable {
    case noAccess = "NoAccess"
    case preview = "Preview"
    case download = "Download"
    case upload = "Upload"
}
