//
// RestLockInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestLockInfo: Sendable, Codable, JSONEncodable, Hashable {

    public var isLocked: Bool?
    public var owner: String?

    public init(isLocked: Bool? = nil, owner: String? = nil) {
        self.isLocked = isLocked
        self.owner = owner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isLocked = "IsLocked"
        case owner = "Owner"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isLocked, forKey: .isLocked)
        try container.encodeIfPresent(owner, forKey: .owner)
    }
}

