//
// RestTemplateNode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestTemplateNode: Sendable, Codable, JSONEncodable, Hashable {

    public var children: [String: TreeNode]?
    public var node: TreeNode?

    public init(children: [String: TreeNode]? = nil, node: TreeNode? = nil) {
        self.children = children
        self.node = node
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case children = "Children"
        case node = "Node"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(node, forKey: .node)
    }
}

