//
// RestActionParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestActionParameters: Sendable, Codable, JSONEncodable, Hashable {

    public var awaitStatus: JobsTaskStatus?
    public var awaitTimeout: String?
    public var jsonParameters: String?
    public var nodes: [RestNodeLocator]?
    public var selectionUuid: String?
    public var targetNode: RestNodeLocator?

    public init(awaitStatus: JobsTaskStatus? = nil, awaitTimeout: String? = nil, jsonParameters: String? = nil, nodes: [RestNodeLocator]? = nil, selectionUuid: String? = nil, targetNode: RestNodeLocator? = nil) {
        self.awaitStatus = awaitStatus
        self.awaitTimeout = awaitTimeout
        self.jsonParameters = jsonParameters
        self.nodes = nodes
        self.selectionUuid = selectionUuid
        self.targetNode = targetNode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case awaitStatus = "AwaitStatus"
        case awaitTimeout = "AwaitTimeout"
        case jsonParameters = "JsonParameters"
        case nodes = "Nodes"
        case selectionUuid = "SelectionUuid"
        case targetNode = "TargetNode"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(awaitStatus, forKey: .awaitStatus)
        try container.encodeIfPresent(awaitTimeout, forKey: .awaitTimeout)
        try container.encodeIfPresent(jsonParameters, forKey: .jsonParameters)
        try container.encodeIfPresent(nodes, forKey: .nodes)
        try container.encodeIfPresent(selectionUuid, forKey: .selectionUuid)
        try container.encodeIfPresent(targetNode, forKey: .targetNode)
    }
}

