//
// RestCreateCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public final class RestCreateCheckResponse: Codable, JSONEncodable, Hashable {

    public var results: [RestCheckResult]

    public init(results: [RestCheckResult]) {
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results = "Results"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
    }

    public static func == (lhs: RestCreateCheckResponse, rhs: RestCreateCheckResponse) -> Bool {
        lhs.results == rhs.results
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(results.hashValue)
        
    }
}

