//
// RestNamespaceValuesOperation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestNamespaceValuesOperation: Sendable, Codable, JSONEncodable, Hashable {

    public var operation: RestNsOp
    public var values: [String]

    public init(operation: RestNsOp, values: [String]) {
        self.operation = operation
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case operation = "Operation"
        case values = "Values"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(operation, forKey: .operation)
        try container.encode(values, forKey: .values)
    }
}

