//
// RestMetaUpdateOp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestMetaUpdateOp: String, Sendable, Codable, CaseIterable {
    case put = "PUT"
    case delete = "DELETE"
}
