//
// RestCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestCreateRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var inputs: [RestIncomingNode]
    public var recursive: Bool?

    public init(inputs: [RestIncomingNode], recursive: Bool? = nil) {
        self.inputs = inputs
        self.recursive = recursive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inputs = "Inputs"
        case recursive = "Recursive"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inputs, forKey: .inputs)
        try container.encodeIfPresent(recursive, forKey: .recursive)
    }
}

