//
// RestRevisionMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestRevisionMeta: Sendable, Codable, JSONEncodable, Hashable {

    public var description: String?
    public var uuid: String

    public init(description: String? = nil, uuid: String) {
        self.description = description
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description = "Description"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(uuid, forKey: .uuid)
    }
}

