//
// RestPublishNodeParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPublishNodeParameters: Sendable, Codable, JSONEncodable, Hashable {

    public var cascade: Bool?
    public var promoteLatest: Bool?

    public init(cascade: Bool? = nil, promoteLatest: Bool? = nil) {
        self.cascade = cascade
        self.promoteLatest = promoteLatest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cascade = "Cascade"
        case promoteLatest = "PromoteLatest"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cascade, forKey: .cascade)
        try container.encodeIfPresent(promoteLatest, forKey: .promoteLatest)
    }
}

