//
// RestActionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestActionStatus: String, Sendable, Codable, CaseIterable {
    case performed = "Performed"
    case background = "Background"
}
