//
// RestPromoteVersionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPromoteVersionResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var node: RestNode?
    public var published: Bool?
    public var success: Bool?

    public init(node: RestNode? = nil, published: Bool? = nil, success: Bool? = nil) {
        self.node = node
        self.published = published
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case node = "Node"
        case published = "Published"
        case success = "Success"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(node, forKey: .node)
        try container.encodeIfPresent(published, forKey: .published)
        try container.encodeIfPresent(success, forKey: .success)
    }
}

