//
// RestUserMetaNamespaceCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestUserMetaNamespaceCollection: Sendable, Codable, JSONEncodable, Hashable {

    public var namespaces: [IdmUserMetaNamespace]?

    public init(namespaces: [IdmUserMetaNamespace]? = nil) {
        self.namespaces = namespaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespaces = "Namespaces"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(namespaces, forKey: .namespaces)
    }
}

