//
// RestCreateCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestCreateCheckResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var results: [RestCheckResult]

    public init(results: [RestCheckResult]) {
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results = "Results"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
    }
}

