//
// RestVersionsTypes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RestVersionsTypes: String, Sendable, Codable, CaseIterable {
    case versionsAll = "VersionsAll"
    case draftsOnly = "DraftsOnly"
    case versionsOnly = "VersionsOnly"
}
