//
// RestNodeLocator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestNodeLocator: Sendable, Codable, JSONEncodable, Hashable {

    public var path: String?
    public var uuid: String?

    public init(path: String? = nil, uuid: String? = nil) {
        self.path = path
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path = "Path"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }
}

