//
// RestCheckResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestCheckResult: Sendable, Codable, JSONEncodable, Hashable {

    public var exists: Bool?
    public var inputLocator: RestNodeLocator?
    public var nextPath: String?
    public var node: RestNode?

    public init(exists: Bool? = nil, inputLocator: RestNodeLocator? = nil, nextPath: String? = nil, node: RestNode? = nil) {
        self.exists = exists
        self.inputLocator = inputLocator
        self.nextPath = nextPath
        self.node = node
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exists = "Exists"
        case inputLocator = "InputLocator"
        case nextPath = "NextPath"
        case node = "Node"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(exists, forKey: .exists)
        try container.encodeIfPresent(inputLocator, forKey: .inputLocator)
        try container.encodeIfPresent(nextPath, forKey: .nextPath)
        try container.encodeIfPresent(node, forKey: .node)
    }
}

