//
// RestPreSignedURL.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPreSignedURL: Sendable, Codable, JSONEncodable, Hashable {

    public var expiresAt: String?
    public var url: String?

    public init(expiresAt: String? = nil, url: String? = nil) {
        self.expiresAt = expiresAt
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt = "ExpiresAt"
        case url = "Url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

