//
// RestPublicLinkDeleteSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RestPublicLinkDeleteSuccess: Sendable, Codable, JSONEncodable, Hashable {

    public var message: String?
    public var uuid: String?

    public init(message: String? = nil, uuid: String? = nil) {
        self.message = message
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message = "Message"
        case uuid = "Uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }
}

