//
// ServiceResourcePolicyQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServiceResourcePolicyQuery: Sendable, Codable, JSONEncodable, Hashable {

    public var action: ServiceResourcePolicyAction?
    public var any: Bool?
    public var empty: Bool?
    public var leftIdentifier: String?
    public var subjects: [String]?

    public init(action: ServiceResourcePolicyAction? = nil, any: Bool? = nil, empty: Bool? = nil, leftIdentifier: String? = nil, subjects: [String]? = nil) {
        self.action = action
        self.any = any
        self.empty = empty
        self.leftIdentifier = leftIdentifier
        self.subjects = subjects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action = "Action"
        case any = "Any"
        case empty = "Empty"
        case leftIdentifier = "LeftIdentifier"
        case subjects = "Subjects"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(any, forKey: .any)
        try container.encodeIfPresent(empty, forKey: .empty)
        try container.encodeIfPresent(leftIdentifier, forKey: .leftIdentifier)
        try container.encodeIfPresent(subjects, forKey: .subjects)
    }
}

