//
// ServiceResourcePolicyAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ServiceResourcePolicyAction: String, Sendable, Codable, CaseIterable {
    case any = "ANY"
    case owner = "OWNER"
    case read = "READ"
    case write = "WRITE"
    case editRules = "EDIT_RULES"
}
