//
// StatusFilterDraftStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum StatusFilterDraftStatus: String, Sendable, Codable, CaseIterable {
    case draftNot = "DraftNot"
    case draftOnly = "DraftOnly"
    case draftAny = "DraftAny"
}
