//
// StatusFilterDeletedStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum StatusFilterDeletedStatus: String, Sendable, Codable, CaseIterable {
    case not = "Not"
    case only = "Only"
    case any = "Any"
}
