//
// TreeNodeChangeEventEventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TreeNodeChangeEventEventType: String, Sendable, Codable, CaseIterable {
    case create = "CREATE"
    case read = "READ"
    case updatePath = "UPDATE_PATH"
    case updateContent = "UPDATE_CONTENT"
    case updateMeta = "UPDATE_META"
    case updateUserMeta = "UPDATE_USER_META"
    case delete = "DELETE"
}
